name: Build and push container

on:
  [push]

env:
  GITHUB_TOKEN: ${{ github.token }}
  URL: https://raw.githubusercontent.com/DevOps-and-Cloud-based-Software/week1/${{ github.ref_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Replace links
        run: |
          cp README.md README_WITH_LINKS.md 
          sed -i -e "s#src=\"/images/#src=\"$URL/images/#g" README_WITH_LINKS.md 
          for file in sources/*; do sed -i -e "s#($file)#($URL/$file)#g" README_WITH_LINKS.md ; done
         

      - name: Check links
        run: |
          grep -o "http[^ ]*" README_WITH_LINKS.md | sed '/.*localhost/d' | sed '/.*NODE_PORT/d' > links
          

      - name: Check URLs
        uses: paramt/url-checker@master
        with:
          files: "README_WITH_LINKS.md"
          

      - name: Publish PDF Document
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'README_WITH_LINKS.md'



      - name: Upload Document
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: 'week1Lab'
          path: ${{ steps.publish-document.outputs.pdf }}

      - name: Upload README_WITH_LINKS.md
        uses: actions/upload-artifact@v2
        id: upload-readme-file
        with:
          name: 'README_WITH_LINKS.md'
          path: README_WITH_LINKS.md