name: replace links
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: nguyenvanuyn96/str-find-and-replace-action@master
        with:
          find: "Docker"
          replace: "Singularity"
          include: "README-WITH-links.md"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}