name: test postman files
on: [push]

jobs:
  test-postman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run docker
      run: |
        docker run -d -p 80:80  nginx && \
          docker ps && sleep 1

    - name: "Check files existence"
      uses: andstor/file-existence-action@v2
      with:
        files: "sources/collection.json,sources/environment.json"
        fail: true

    - name: Replace links
      run: |
        cp README.md README_WITH_LINKS.md 
        sed -i -e "s#172.17.0.2:8080#localhost#g" sources/environment.json
        for file in sources/*; do sed -i -e "s#($file)#($URL/$file)#g" README_WITH_LINKS.md ; done

    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@master
      with:
        collection: sources/collection.json
        environment: sources/environment.json
        reporters: cli
        envVar: '[{ "key": "baseUrl", "value": "http://localhost/tutorial/1.0.0/" }]'
        bail: false