name: test-k8s-files

on:
  [push]

jobs:
  test-k8s-files:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - uses: balchua/microk8s-actions@v0.3.0
        with:
          channel: '1.25/stable'
          addons: '["dns", "rbac", "hostpath-storage", "registry", "metrics-server"]'
      - name: Test MicroK8s
        id: k8s
        run: |
          kubectl apply -f sources/student_service.yaml
          kubectl get pods -A -o wide