name: test jsons

on:
  [push]

jobs:
  test-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: check postman files
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: sources/collection.json
          environment: sources/environment.json
          reporters: cli
          iterationCount: 1