name: test

on:
  [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check URLs
        uses: paramt/url-checker@master
        with:
          files: "README.md"
